version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "800:800"
  web1:
    build: ./web
    ports:
     - "3000"
  web2:
    build: ./web
    ports:
     - "3000"
  web3:
    build: ./web
    ports:
     - "3000"
  redis-master:
    image: "redis"
  redis-slave:
    image: "redis"
    command: redis-server --slaveof redis-master 6379
